name: Build and Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - "*"

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

env:
  FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}

jobs:
  build:
    name: Build and test
    runs-on: ubuntu-20.04
    env:
      MIX_ENV: test
    strategy:
      matrix:
        elixir: ["1.14.0"]
        otp: ["24.3.4.3"]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Elixir Project
        uses: ./.github/actions/elixir-setup
        with:
          elixir-version: ${{ matrix.elixir }}
          otp-version: ${{ matrix.otp }}
          build-flags: --all-warnings --warnings-as-errors

      # Run if you have a database
      # - name: Run Migrations
      #   run: mix ecto.migrate
      #   # Run tests & migrations even if compilation failed (probably due to warnings)
      #   # so that we give devs as much feedback as possible & save some time.
      #   if: always()

      - name: Run Tests
        run: mix test --warnings-as-errors
        if: always()

      # Optional, but Codecov has a bot that will comment on your PR with per-file
      # coverage deltas.
      # - name: Upload to Codecov
      #   uses: codecov/codecov-action@v1
      #   with:
      #     token: ${{ secrets.CODECOV_TOKEN }} # not required for public repos
      #     files: ./cover/excoveralls.json

  deploy:
    name: Deploy to Fly.io
    if: github.ref == 'refs/heads/main'
    needs: build
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: superfly/flyctl-actions@1.3
        with:
          args: "deploy storybook --remote-only"
